### ISSUE TITLE
assignment-3 Fibonacci sequence

### ISSUE THREAD

**Issue by 56bit23** [vtcbca/basic-programming-58bit23#2]
How do you initialize the Fibonacci sequence in the program?

**Comment by 58bit23** [comment]
Starts with two variables

**Comment by 56bit23** [comment]
Define Fibonacci sequence.

**Comment by 58bit23** [comment]
The Fibonacci sequence is a series of numbers in which each number is the sum of the two preceding ones.

**Comment by 56bit23** [comment]
Can I get a example of fibonacci sequence?

**Comment by 58bit23** [comment]
Yes here it is
0,1,1,2,3,5,8,13.........

**Comment by 56bit23** [comment]
OK now I've undertand it

**Comment by 58bit23** [comment]
Yes It is damn simple

**Comment by 56bit23** [comment]
Thank you @56bit23 to clear me the concept of fibonacci sequence
