### ISSUE TITLE
Assignment 5-Palindrome Checker

### ISSUE THREAD

**Issue by 45bit23** [vtcbca/basic-programming-58bit23#3]
What do you mean by Palindrome ?

**Comment by 58bit23** [comment]
A palindrome is a word, phrase, number, or other sequence of characters that reads the same backward as forward, ignoring spaces, punctuation, and capitalization.

**Comment by 45bit23** [comment]
What is an example of a palindrome?

**Comment by 58bit23** [comment]
12321
In above example you can see the number can also be seen the same if you reverse it.

**Comment by 45bit23** [comment]
oh it's the method to check the palindrome?

**Comment by 58bit23** [comment]
Yes

**Comment by 45bit23** [comment]
Is 17 a palindrome?

**Comment by 58bit23** [comment]
No it is not

**Comment by 45bit23** [comment]
Is palindrome important?

**Comment by 58bit23** [comment]
Yes, it is important in Puzzle Games, DNA sequence, Poems for make rhyming, etc...

**Comment by 45bit23** [comment]
That's great it's really helpful for me Thank you so much

**Comment by 58bit23** [comment]
You're Welcome
