### ISSUE TITLE
Assignment-2 Prime number

### ISSUE THREAD

**Issue by 47bit23** [vtcbca/basic-programming-58bit23#5]
What is prime number ?

**Comment by 58bit23** [comment]
Prime numbers are those natural number divisible by only 1 and the number itself. Numbers with more than two factors are called composite numbers All primes are odd numbers except for 2.

**Comment by 47bit23** [comment]
Can you explain it with a simple example ??

**Comment by 58bit23** [comment]
Here are some example given below
2,3,5,7,11,13

**Comment by 47bit23** [comment]
How do you determine if a number is prime?

**Comment by 58bit23** [comment]
**By following methods we can determine prime numbers efficiently:**

1. Small Numbers: n≤1 are not prime; 2 and 3 are prime.
2. Divisors: Check divisors up to square root of n to reduce unnecessary checks.
3. Edge Cases: Handle even numbers and multiples of 3 separately for efficiency.

**Comment by 47bit23** [comment]
Can negative numbers be prime? Why or why not?

**Comment by 58bit23** [comment]
No, negative numbers cannot be prime.

**Comment by 47bit23** [comment]
Gotcha understand all the concept !!

**Comment by 58bit23** [comment]
Yeah it is a damn easy concept

**Comment by 47bit23** [comment]
Thanks !!!

**Comment by 58bit23** [comment]
It was mine pleasure.
